# Generated by Django 5.1.3 on 2024-11-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productscrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metainfo',
            name='barcode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
